# Generated by Django 3.0.7 on 2020-09-01 21:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_manager', '0009_auto_20200901_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', mdeditor.fields.MDTextField()),
                ('status', models.IntegerField(choices=[(0, '未读'), (1, '已读')], default=0, verbose_name='状态')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2020, 9, 1, 21, 20, 14, 208723), verbose_name='添加时间')),
                ('create_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_user', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_manager.Project')),
                ('receive_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receive_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '工作日记',
                'verbose_name_plural': '工作日记',
            },
        ),
    ]
