# Generated by Django 3.0.3 on 2020-05-21 15:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.IntegerField(default=0, verbose_name='新问题')),
                ('solved', models.IntegerField(default=0, verbose_name='已解决问题')),
                ('unresolved', models.IntegerField(default=0, verbose_name='待解决问题')),
                ('createtime', models.DateTimeField(default=datetime.datetime(2020, 5, 21, 15, 24, 55, 231651), verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='问题名')),
                ('dept', models.CharField(max_length=40, null=True, verbose_name='部门')),
                ('show', mdeditor.fields.MDTextField()),
                ('status', models.IntegerField(choices=[(0, '待反馈'), (1, '待解决'), (2, '已解决')], default=0, verbose_name='状态')),
                ('successinfo', models.CharField(max_length=255, null=True, verbose_name='完成信息')),
                ('successtime', models.DateTimeField(null=True, verbose_name='完成时间')),
                ('createtime', models.DateTimeField(default=datetime.datetime(2020, 5, 21, 15, 24, 55, 231105), verbose_name='添加时间')),
                ('mod', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_manager.Mod')),
                ('project', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_manager.Project')),
                ('user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
            },
        ),
    ]
