# Generated by Django 3.0.3 on 2020-05-21 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_manage', '0003_auto_20200521_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 15, 48, 52, 632622), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='questionstatistics',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 15, 48, 52, 633147), verbose_name='添加时间'),
        ),
    ]
