# Generated by Django 3.0.3 on 2020-05-21 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_manage', '0004_auto_20200521_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='deptid',
            field=models.IntegerField(default=0, verbose_name='单位编码'),
        ),
        migrations.AddField(
            model_name='question',
            name='docno',
            field=models.IntegerField(default=0, verbose_name='单据号'),
        ),
        migrations.AddField(
            model_name='question',
            name='indexno',
            field=models.IntegerField(default=0, verbose_name='指标号'),
        ),
        migrations.AddField(
            model_name='question',
            name='qname',
            field=models.CharField(default=0, max_length=255, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='question',
            name='qphone',
            field=models.IntegerField(default=0, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='question',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 20, 20, 54, 953939), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='questionstatistics',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 20, 20, 54, 954501), verbose_name='添加时间'),
        ),
    ]
