# Generated by Django 3.0.3 on 2020-05-21 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_manage', '0005_auto_20200521_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 20, 29, 19, 672831), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='deptid',
            field=models.CharField(default=0, max_length=255, verbose_name='单位编码'),
        ),
        migrations.AlterField(
            model_name='question',
            name='docno',
            field=models.CharField(default=0, max_length=25, verbose_name='单据号'),
        ),
        migrations.AlterField(
            model_name='question',
            name='indexno',
            field=models.CharField(default=0, max_length=255, verbose_name='指标号'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qphone',
            field=models.CharField(default=0, max_length=255, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='questionstatistics',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 20, 29, 19, 673374), verbose_name='添加时间'),
        ),
    ]
