# Generated by Django 3.0.7 on 2020-09-01 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_manage', '0008_auto_20200617_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 21, 20, 14, 181729), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='deptid',
            field=models.CharField(default=0, max_length=255, null=True, verbose_name='单位编码'),
        ),
        migrations.AlterField(
            model_name='question',
            name='docno',
            field=models.CharField(default=0, max_length=25, null=True, verbose_name='单据号'),
        ),
        migrations.AlterField(
            model_name='question',
            name='indexno',
            field=models.CharField(default=0, max_length=255, null=True, verbose_name='指标号'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qname',
            field=models.CharField(default=0, max_length=255, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qphone',
            field=models.CharField(default=0, max_length=255, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='questionstatistics',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 21, 20, 14, 183729), verbose_name='添加时间'),
        ),
    ]
