# Generated by Django 3.0.3 on 2020-05-21 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manager', '0003_auto_20200521_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 15, 48, 52, 631246), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 15, 48, 52, 631639), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 15, 48, 52, 632013), verbose_name='添加时间'),
        ),
    ]
