# Generated by Django 3.0.3 on 2020-06-17 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manager', '0007_auto_20200616_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 11, 5, 42, 640116), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 11, 5, 42, 640690), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 11, 5, 42, 641470), verbose_name='添加时间'),
        ),
    ]
