# Generated by Django 3.0.7 on 2020-09-01 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manager', '0008_auto_20200617_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 21, 20, 14, 179730), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 21, 20, 14, 180730), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 21, 20, 14, 180730), verbose_name='添加时间'),
        ),
    ]
