# Generated by Django 3.0.3 on 2020-05-21 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='考试名称')),
                ('exam_type', models.IntegerField(choices=[(0, '练习'), (1, '正式')], default=0, verbose_name='类型')),
                ('score', models.IntegerField(default=0, verbose_name='分数')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='考试人')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='所属用户组')),
            ],
            options={
                'verbose_name': '考试信息',
                'verbose_name_plural': '考试信息',
            },
        ),
        migrations.CreateModel(
            name='QuestionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500, verbose_name='试题题目')),
                ('score', models.IntegerField(default=0, verbose_name='分值')),
                ('tq_type', models.IntegerField(choices=[(0, '选择'), (1, '判断'), (2, '填空')], default=0, verbose_name='试题类型')),
                ('is_share', models.BooleanField(default=False, verbose_name='是否分享')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('mod', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='system_manager.Mod', verbose_name='所属模块')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '试题信息',
                'verbose_name_plural': '试题信息',
            },
        ),
        migrations.CreateModel(
            name='OptionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.IntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E'), (5, 'F')], default=0, verbose_name='选项')),
                ('option_content', models.CharField(default='', max_length=255, verbose_name='选项内容')),
                ('is_right', models.BooleanField(default=True, verbose_name='是否为正确答案')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('questioninfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_online.QuestionInfo', verbose_name='试题信息')),
            ],
            options={
                'verbose_name': '试题选项信息',
                'verbose_name_plural': '试题选项信息',
            },
        ),
        migrations.CreateModel(
            name='ExaminationInfoQuestionInfoProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_content', models.CharField(default='', max_length=5000, verbose_name='考试名称')),
                ('is_right', models.BooleanField(default=True, verbose_name='是否为正确')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_online.ExaminationInfo', verbose_name='考试信息')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_online.QuestionInfo', verbose_name='试题信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户信息')),
            ],
            options={
                'verbose_name': '考试_试题_用户',
                'verbose_name_plural': '考试_试题_用户',
            },
        ),
    ]
