# Generated by Django 3.0.3 on 2020-06-16 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam_online', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinationinfo',
            name='score',
        ),
        migrations.RemoveField(
            model_name='optioninfo',
            name='questioninfo',
        ),
        migrations.RemoveField(
            model_name='questioninfo',
            name='score',
        ),
        migrations.AddField(
            model_name='questioninfo',
            name='type',
            field=models.IntegerField(choices=[(0, '基础类'), (1, '业务类'), (2, '技术类'), (3, '沟通类'), (4, '综合类'), (5, '其他')], default=0, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='questioninfo',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='questioninfo',
            name='updated_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uuser', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questioninfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuser', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
