# Generated by Django 3.0.3 on 2020-06-17 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_online', '0002_auto_20200616_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='optioninfo',
            name='questioninfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam_online.QuestionInfo', verbose_name='试题信息'),
            preserve_default=False,
        ),
    ]
