# Generated by Django 3.0.3 on 2020-05-21 15:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='名称')),
                ('icon', models.CharField(max_length=50, verbose_name='图标')),
                ('type', models.CharField(max_length=25, verbose_name='标签')),
                ('pid', models.CharField(max_length=25, verbose_name='上级ID')),
                ('opentype', models.CharField(default='_iframe', max_length=30, verbose_name='openType')),
                ('href', models.CharField(max_length=90, null=True, verbose_name='href')),
                ('spread', models.CharField(max_length=20, null=True, verbose_name='spread')),
                ('createtime', models.DateTimeField(default=datetime.datetime(2020, 5, 21, 15, 24, 55, 233025), verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
            },
        ),
        migrations.CreateModel(
            name='QuestionStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.IntegerField(default=0, verbose_name='新问题')),
                ('solved', models.IntegerField(default=0, verbose_name='已解决问题')),
                ('unresolved', models.IntegerField(default=0, verbose_name='待解决问题')),
                ('createtime', models.DateTimeField(default=datetime.datetime(2020, 5, 21, 15, 24, 55, 234113), verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '问题统计',
                'verbose_name_plural': '问题统计',
            },
        ),
        migrations.CreateModel(
            name='RoleMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_page.PageMenu')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Role')),
            ],
            options={
                'verbose_name': '角色_菜单',
                'verbose_name_plural': '角色_菜单',
            },
        ),
    ]
