# Generated by Django 3.0.3 on 2020-05-21 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemenu',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 15, 28, 17, 398893), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='questionstatistics',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 15, 28, 17, 399588), verbose_name='添加时间'),
        ),
    ]
