# Generated by Django 3.0.3 on 2020-06-16 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_page', '0006_auto_20200521_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemenu',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 11, 17, 26, 936481), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='questionstatistics',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 11, 17, 26, 937292), verbose_name='添加时间'),
        ),
    ]
